
[package]
name = "spider_eye"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"


[dependencies]

bumpalo = { version = "3.17.0", features = ["collections", "std"] }
byteorder = "1.5.0"
env_logger = "0.11.8"
flate2 = "1.1.1"
fxhash = "0.2.1"
hashbrown = "0.15.3"
num_enum = "0.7.3"
serde = "1.0.219"
serde_json = "1.0.140"
aovec = "1.1.0"
smol_str = "0.3.2"
bytes = "1.10.1"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
heapless = "0.8.0"
fastrand = "2.3.0"
trace = "0.1.7"
simd_cesu8 = { path="../Download/simd_cesu8/", features = ["nightly"] }


[profile.release-with-debug]
inherits = "release"
debug = true

