
[package]
name = "spider_eye"
version = "0.1.0"
edition = "2021"
rust-version = "1.89.0"


[dependencies]

bumpalo = { version = "3.17.0", features = ["collections", "std"] }
byteorder = "1.5.0"
env_logger = "0.11.8"
flate2 = "1.1.1"
fxhash = "0.2.1"
hashbrown = { version = "0.15.3", features = ["serde", "nightly", "rayon"] }
num_enum = "0.7.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
aovec = "1.1.0"
bytes = "1.10.1"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
heapless = "0.8.0"
fastrand = "2.3.0"
trace = "0.1.7"
simd_cesu8 = { path="../Download/simd_cesu8/", features = ["nightly"] }
compact_str = "0.9.0"
lasso = { version = "0.7.3", features = ["inline-more", "ahasher"] }
mimalloc = "0.1.47"
simd-json = "0.15.1"
simd-json-derive = "0.16.1"
serde_with = "3.14.0"
rayon = "1.11.0"


[profile.release-with-debug]
inherits = "release"
debug = true
codegen-units=1
lto="fat"


[profile.release]
lto="fat"
codegen-units=1

