[package]
name = "mc_utils"
version = "0.1.0"
edition="2024"

[dependencies]
bumpalo = { version = "3.17.0", features = ["collections", "std"] }
byteorder = "1.5.0"
env_logger = "0.11.8"
flate2 = "1.1.1"
fxhash = "0.2.1"
num_enum = "0.7.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
aovec = "1.1.0"
bytes = "1.10.1"
tracing = "0.1.41"
heapless = "0.9.2"
fastrand = "2.3.0"
simd_cesu8 = { version ="1.1.0", features = ["nightly"] }
compact_str = "0.9.0"
lasso = { version = "0.7.3", features = ["inline-more", "ahasher"] }
mimalloc = "0.1.47"
simd-json = "0.17.0"
simd-json-derive = "0.18.0"
serde_with = "3.14.0"
rayon = "1.11.0"
cesu8-str = "1.2.1"
thiserror = "2.0.17"
tracing-test = "0.2.5"
hashbrown = { version = "0.16.1", features = ["rayon", "serde"] }


[profile.release-with-debug]
inherits = "release"
debug = true

